name: Backend Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . -t nietrenswens/levendmonopoly-backend:latest

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/levendmonopoly-backend

    - name: Pull the image to VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASS }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/levendmonopoly-backend:latest
          docker stop levendmonopoly-backend || true
          docker rm levendmonopoly-backend || true
          mkdir -p ${HOME}/.aspnet/https/aspnetapp.pfx
          dotnet dev-certs https -ep ${HOME}/.aspnet/https/aspnetapp.pfx -p ${{ secrets.SSH_PASS }}
          dotnet dev-certs https --trust
          docker run -d -p 5000:5000 -p 5001:5001 -e ASPNETCORE_URLS="https://+;http://+" -e ASPNETCORE_HTTPS_PORTS=5001 ASPNETCORE_Kestrel__Certificates__Default__Password="${{ secrets.SSH_PASS }}" -e ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx -v ${HOME}/.aspnet/https:/https/ --name levendmonopoly-backend ${{ secrets.DOCKERHUB_USERNAME }}/levendmonopoly-backend:latest
